server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
    #修改返回前端的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sany.pojo
  configuration:
    map-underscore-to-camel-case: true