server:
  port: 80

spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      #表示8001端口入驻consul的名称，就是服务的发现
      discovery:
        service-name: ${spring.application.name}

  application:
    name: cloud-consumer-order